apm-server:
  host: "0.0.0.0:8200"
  frontend.enabled: true

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
setup.template.enabled: true
setup.template.name: "apm-%{[observer.version]}"
setup.template.pattern: "apm-%{[observer.version]}-*"
setup.template.fields: "${path.config}/fields.yml"
setup.template.overwrite: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "logstash"
  password: "logstash123"
  enabled: true
  index: "apm-%{[observer.version]}-%{+YYYY.MM.dd}"

logging.level: info
logging.selectors: ["*"]
logging.to_files: true
logging.files:
  path: /var/log/apm-server
  name: apm-server.log
  rotateeverybytes: 10485760 # = 10MB
  keepfiles: 7

monitoring:
  enabled: true
  elasticsearch:
    username: elk-user
    password: userpass123
